sudo: requried

services:
  - docker

before_install:
  - docker -v
  - docker-compose -v

install:
  - curl -sSL http://bit.ly/2ysbOFE | bash -s
  - docker images
  
script:
  - pwd
  - ls -l
  - cd first-network
  - echo "----E2E Starts----"
  - ./byfn.sh up -o kafka

after_script:
  - ./byfn.sh down -o kafka
